### ISSUE TITLE
Split Inventory.updateInventory to several methods

### ISSUE THREAD

**Issue by AKryukov92** [DreamBlocks/DreamBlocks#12]
At version 42639a5, method Inventory.updateInventory contains a lot of conditions and loops and 141 line long. I think it should be split to several methods. 
I expect all those methods will be a members of Inventory class but it is not mandatory.
All methods should be named properly in english.

**Comment by SonyaSitnikova** [comment]
В версии 42639a5 метод Inventory.updateInventory содержит множество условий и циклов и длину 141 строка. Я думаю, что он должен быть разделен на несколько методов.
Я ожидаю, что все эти методы будут членами класса Inventory, но это не обязательно.
Все методы должны быть правильно названы на английском языке.

**Comment by RodrigueLemaire** [comment]
@SonyaSitnikova please write in english or use reverso.net

> In version 42639a5 method Inventory.updateInventory contains plenty of the conditions and cycles and length 141 line. I think that he should be divided to a few methods.
> I expect that all these methods will be the members of the class Inventory, but it is not obligatory.
> All methods should be properly named in English.

**Comment by AKryukov92** [comment]
@azekillDIABLO It was a translation of initial message to our native language.

**Comment by AKryukov92** [comment]
I'm going to implement it in nearest future.
