### ISSUE TITLE
Sprite should not draw itself

### ISSUE THREAD

**Issue by AKryukov92** [DreamBlocks/DreamBlocks#13]
At version 42639a5 class Sprite contains method draw, which takes GraphicHandler as argument and some drawing parameters.
This approach led to passing GraphicsHandler to every drawing function. In the end, GraphicsHandler will do drawing, not the Sprite.
I think that method 'draw' should be moved to GraphicsHandler class. It should take Sprite as argument.

There are some special cases with Inventory class. It should not change at this moment.

**Comment by SonyaSitnikova** [comment]
По версии 42639a5 класса Sprite содержит метод Draw, который принимает GraphicHandler в качестве аргумента и некоторые параметры отображения. Этот подход привел к прохождению GraphicsHandler к каждой функции рисования. В конце концов, GraphicsHandler сделаем чертеж, а не спрайт. Я думаю, что метод "нарисовать" должны быть перемещены в GraphicsHandler класс. Надо взять спрайт в качестве аргумента. Существует несколько особых случаев, с класс Inventory. Он не должен меняться в этот момент.
