### ISSUE TITLE
SGL2D (Simple Game Library 2D)

### ISSUE THREAD

**Issue by LordStephen77** [DreamBlocks/DreamBlocks#17]
To solve the old addictions of the game, I have been working on a small framework for writing 2D games written in Java for some time. This library is a collection of optimized and redefined code snippets for JDK 8. SGL2D (Simple Game Library 2D) is a very simple framework that works as a wrapper with the standard Java library. Does not use any external dependence! and not even JavaFX.

I'm going to test it shortly inside DreamBlocks. At the moment it contains everything you need to improve and simplify the project.

In the repository you find the project at the current state, which also contains the doc (javadoc) folder. If you are interested go to see. I have to work on the wiki to make some examples and first documentation to showcase the main features of the library.

The project was born as a study and research material. I've been thinking of rebuilding it to make this library the best solution for DreamBlocks. of course SGL2D allows you to develop 2D games of any kind! Only the module for the controller (Gamepad) is missing.

<br>

**Features:**

<br>

- Simple input / update / drawing chain
- Sprite sheet parsing
- Animations
- Sounds
- Easy camera movement
- Network classes
- 2D noise (e.g. for terrain generation)
- Read and write files and images easily

<br>

SGL2D only uses standard Java APIs, which makes it highly portable.

<br>

**Official repository:**

<br>

https://github.com/SGL2D

<br>

**Comment by AKryukov92** [comment]
I don't understand why you opened this issue.
Do you want to migrate DreamBlocks to SGL2D? Or do you just want to promote it?

**Comment by LordStephen77** [comment]
@AKryukov92 I was going to show it to decide if it's a good idea to integrate SGL2D into the DreamBlocks project. Simplifies procedures such as image, sound management, and more. I have to work on it, but I think it will be useful.

I wanted your personal opinion. If you are interested, if you find a good choice. I'm not a professional programmer, and I love the standard Java library. For this reason I decided to adopt SGL2D.

I hope I was clear. My English is bad! I apologize :)

**Comment by AKryukov92** [comment]
I'm asking because I need this project as it is written at this moment. It is quite messy, thats why it is perfect educational material for students, who needs practice with java. It will take a lot of effort to write bad code for me. It is possible to formulate simple tasks to implement. And those tasks will not require detailed studying of codebase. I have already showed repository to two of my "best" students.

I'm not against of using SGL2D, but in this case we need to make detailed description of GAME itself.
For example:
What goals are we going to set for player?
How players are supposed to reach those goals?
What activities should be available for player?

**Comment by LordStephen77** [comment]
@AKryukov92 I had no doubt you were a university professor! I understand it immediately by reading what you are writing and the code that you made. Your answer was very satisfying, I have a lot to learn from you.

At this time, the priority is to fix the main bugs, improve game play (inventory, hotbar).

These days I have a lot of work, but I want to test the splash screen and the new experimental gaming menu.

Thanks for your valuable advice. I seriously think of making you a project admin to give you all unrestricted access. DreamBlocks is a good project to learn and I hope it can be of help to your students.

As soon as I get free, I take note of all the things I want to add later.

Thank you.

**Comment by AKryukov92** [comment]
After some experiments, I have decided that this project at this state seems to be too complex for beginners.
I'll switch to synthetic tasks for them. Please do not be constrained in choosing of any additional library for it.
