### ISSUE TITLE
can a launcher be added

### ISSUE THREAD

**Issue by tobyplowy** [DreamBlocks/DreamBlocks#20]
we all know hat a launcher does so no need to explane

**Comment by AKryukov92** [comment]
I do know what launcher is, but I don't understand why it needs to be implemented.
Explain your proposal, please.

**Comment by tobyplowy** [comment]
Well it's an easier way to update the game instead of having to re install the jar a hundred times

**Comment by tobyplowy** [comment]
Also it can be used for news in development of the game

**Comment by AKryukov92** [comment]
I think it is possible to make a script (batch or shell), which will check directory in google drive and download file, if the game were updated, and then run the game after that.
But there is not much news to publish. Website should manage it.

**Comment by tobyplowy** [comment]
> But there is not much news to publish.

Not yet

**Comment by AKryukov92** [comment]
First of all, I don't have time and skills to prepare news. I'd like to stay with coding.
If someone starts to produce news about project, it will be great.
But I think that website or facebook group or twitter channel or any other social network public page will do the job of delivering news much better than launcher.
People don't need to download facebook, right?

**Comment by tobyplowy** [comment]
Ok you are right
