### ISSUE TITLE
Use inventory visual layout made by @tobyplowy

### ISSUE THREAD

**Issue by AKryukov92** [DreamBlocks/DreamBlocks#24]
Follow this link to see layout
https://files.gitter.im/LordStephen77/Lobby/iGfL/Screenshot-_33_.png
Right now there are no armor slots, so they should not be drawn.

@tobyplowy please tell how do you made title "INVENTORY". Which font is used? If it is just a picture, could you add it to this thread?

**Comment by LordStephen77** [comment]
Right! Guys always make notes about the realization of your work. It is useful to create doc for the project and follow a linear workflow.

**Comment by tobyplowy** [comment]
@AKryukov92 The font is Made Up By Me (I made it myself) I've Been using it for the whole 7 Years I have been doing pixelart :)
I can give you a picture of the whole alfabet if you whant

**Comment by tobyplowy** [comment]
@LordStephen77 I'm not really sure what you mean by that 

Do you mean we should plan out everything before we do?

**Comment by AKryukov92** [comment]
@tobyplowy Of course we need whole alphabet.

@LordStephen77 probably meant that any change in repository should be made as a result of the task.
Git automatically assigns numbers for each task. When you commit, you type number of the task alongside with commit description. It allows for git to display commits in the issue threads.
See example here https://github.com/DreamBlocks/DreamBlocks/issues/18

**Comment by tobyplowy** [comment]
@AKryukov92 ok sorry

Ok thanks for explaining

**Comment by AKryukov92** [comment]
I think that best place for images is Dreamblocks/res/sprites/alphabet
There should be only one letter per sprite

**Comment by tobyplowy** [comment]
I don't know how to make pull requests

**Comment by AKryukov92** [comment]
You need to:
* fork this project
* make branch in your fork
* commit changes to your fork
* submit pull request

Detailed explanation is here https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by LordStephen77** [comment]
@tobyplowy Write the technique you use to create content, type of font used (name), small nights that help future collaborators understand what we did.

**Comment by tobyplowy** [comment]
@AKryukov92 I think I did it

**Comment by AKryukov92** [comment]
@tobyplowy Thats a good start.
At this moment, I think it will be difficult to extract characters from this file programmatically.
Can you add description file. It should contain multiple rows. One row per character.
In each row you need to write letter, its x and y coordinates (in pixels) on the picture, width and height. Values should be separated by ";"
Something like
```
A;0;0;4;6
B:5;0;4;6
```

**Comment by tobyplowy** [comment]
i made the toolbar easier to see
![screenshot-_33_](https://user-images.githubusercontent.com/16853304/27509546-ee930ec4-58ff-11e7-8f6d-d72c32896173.png)

**Comment by tobyplowy** [comment]
> @tobyplowy Thats a good start.
> At this moment, I think it will be difficult to extract characters from this file programmatically.
> Can you add description file. It should contain multiple rows. One row per character.
> In each row you need to write letter, its x and y coordinates (in pixels) on the picture, width and height. Values should be separated by ";"
> Something like

oh god i dount really have the time for that :/
maybe making all letters and mumbers a separit picture is fasterer and better?

**Comment by AKryukov92** [comment]
Letters and numbers in separate pictures are good option too.
For letters, which can't be used in filenames, use html entities like `&#8725;` for '\\'

**Comment by tobyplowy** [comment]
@AKryukov92 no I mean make each letter and number an new picture

This will make adding more letters and simbols easyer

**Comment by tobyplowy** [comment]
@AKryukov92 or maybe we should just use a font file .ttf (pixelmix is nice but I don't know if the licence allows this kind of use)

**Comment by tobyplowy** [comment]
@AKryukov92 shuld we go with a font file (.ttf) @LordStephen77 approves this idea

**Comment by AKryukov92** [comment]
I'm all for using .ttf It will make implementation of buttons more flexible.

@tobyplowy Please add a :open crafting guide" button to inventory layout.

**Comment by tobyplowy** [comment]
@AKryukov92 there you go
![screenshot-_33_](https://user-images.githubusercontent.com/16853304/27596716-a576f710-5b60-11e7-86df-6f83f063621d.png)

**Comment by AKryukov92** [comment]
I don't understand what are those 4 cells in top-right corner. Why you grouped them with crafting guide together?

**Comment by tobyplowy** [comment]
those were in the original gui so i added them 
i think its for armor

i grouped them together for astethic reasons otherwise it looks odd

**Comment by tobyplowy** [comment]
also craft guide gui
![screenshot-_33_ - kopie](https://user-images.githubusercontent.com/16853304/27597889-07c526f0-5b64-11e7-8383-9941598e3616.png)

**Comment by AKryukov92** [comment]
I'm asking because button "open crafting guide" looks like a place for armor.

**Comment by tobyplowy** [comment]
The 4 slots are for armor and the one button with the 9 squares is craft guide 

Shuld I remove the armor slots?

**Comment by AKryukov92** [comment]
I am sure that you shouldn't group armor with "crafting guide button".
As long as armor is not implemented, in the game there will be no visible slots. But we need to know where they will be located.

**Comment by AKryukov92** [comment]
One more thing that I don't like in MC and MT is that you need to click thousand times to process all resources. There are shift+click combinations, but they are not obvious. What are yours proposal regarding this?

**Comment by tobyplowy** [comment]
@AKryukov92 I think it is fine (as long as there if shift+click) maybe you can add a tooltip if you hover over the create slot saying that you can shift+click to make more?

**Comment by AKryukov92** [comment]
I have found a site with open source pixel fonts.
What about:
*  disposable droid http://www.1001fonts.com/disposabledroid-bb-font.html
* pixel FJVerdana http://www.1001fonts.com/pix-pixelfjverdana12pt-font.html
* Munro https://www.fontsquirrel.com/fonts/Munro

**Comment by tobyplowy** [comment]
@AKryukov92 I like Munro most

**Comment by AKryukov92** [comment]
Discussion continues here https://github.com/DreamBlocks/DreamBlocks/issues/38
There are latest version of inventory layout.
