### ISSUE TITLE
Missing dependencies in gradle

### ISSUE THREAD

**Issue by AKryukov92** [DreamBlocks/DreamBlocks#3]
At version 0f22fe3, I can't run the project because of missing dependencies in gradle.

**Comment by AKryukov92** [comment]
Currently I have problems pushing changes to this repository.
Error message says: `Failed with error: fatal: unable to access 'https://github.com/DreamBlocks/DreamBlocks.git/': The requested URL returned error: 403`
I assume @LordStephen77 should configure access.

**Comment by LordStephen77** [comment]
@AKryukov92 You are much better than me with github and gradle. I've seen you're solving dependencies in Grande. It would be useful for a small docs where we note these things, as well as always comment on the code as much as possible. I want to make the project accessible to students, hobbyists, anyone with a minimum of knowledge in java. Thank you so much for your precious contribution.

**Comment by AKryukov92** [comment]
I think it is better to ask questions. I don't know what it unclear to you.
Gradle has good documentation regarding solving dependencies. I just opened it and followed the instructions.

**Comment by LordStephen77** [comment]
Yes, for this use Gradle. But I've been out here for a few hours, and I did not have time to control everything. Thanks for your help. It draws my distraction from fatigue. Thanks so much.

**Comment by AKryukov92** [comment]
You are welcome

**Comment by AKryukov92** [comment]
Dependencies are in list, but it still fails to compile with gradle. I'm wondering why it did 2 hours ago.

**Comment by AKryukov92** [comment]
Timer and ogg player were declared as local file dependencies, but they were ignored and not commited.
Thats why project failed to compile.

**Comment by AKryukov92** [comment]
Somebody else please check: if everything OK now. if it is, then close issue, please.

**Comment by LordStephen77** [comment]
I accepted the commit. It seems all right now. I close.
