### ISSUE TITLE
Make InventorySlot as separate class

### ISSUE THREAD

**Issue by AKryukov92** [DreamBlocks/DreamBlocks#31]
There are a lof ot pixel math involved with operations on inventory items.
* Inventory should compute their bounds on each redraw.
* To check if mouse is pointing to specific inventory item, Inventory should compute its bounds again.
And there are a lot of methods, which operate only on one slot.
Probably whole handling of clicks on inventory slots should be moved to InventorySlot.

**Comment by SonyaSitnikova** [comment]
translation into Russian language

**Comment by AKryukov92** [comment]
I am going to implement this in nearest future.

**Comment by AKryukov92** [comment]
Class InventorySlot should contain fields:
* InventoryItem source
and methods:
* public void draw(GraphicsHandler g, int x, int y, int tileSize, int seperation)
* public void handleLeftClick(InventoryItem holding)
* public void handleRightClick(InventoryItem holding)

Methods should be taken from existing class InventoryItem.

Following fields should be added to class Inventory:
* InventorySlot[][] backpack

It should be initialized using field `inventoryItems`
Method `drawBackpack` should call methods `draw` of elements of field `backpack`.
Method `handleClick` should call methods `handleLeftClick` and `handleRightClick` of elements of field `backpack`.
