### ISSUE TITLE
Split code in game loop to several methods

### ISSUE THREAD

**Issue by AKryukov92** [DreamBlocks/DreamBlocks#5]
At revision be761e9, body of loop in method gameLoop() of src/main/java/com/lgs/dreamblocks/MainGame.java is 191 line long.
Code inside it should be split to several methods.
I expect all those methods will be members of MainGame class, but it is not mandatory.
All methods should be named properly in English.

**Comment by SonyaSitnikova** [comment]
При пересмотре be761e9 тело цикла в методе gameLoop () из src/main/java/com/lgs/dreamblocks/ MainGame.java имеет длину 191 строка.
Код внутри него должен быть разделен на несколько методов.
Я ожидаю, что все эти методы будут членами класса MainGame, но это не обязательно.
Все методы должны быть правильно названы на английском языке.

**Comment by AKryukov92** [comment]
I have checked this. Everything seems to be OK.
